// Invoice view models — what the browser receives. Pure; safe on client and
// server. Amounts are whole shillings.

import type { LineDiscount, LineDiscountChange } from "@repo/lib/discounts/core/model";
import type { OrderPaymentRecord, PaymentMethod } from "@repo/lib/wallet/types";

export type { OrderPaymentRecord, PaymentMethod };

/** Worked out from the order's price and the payments on it; never stored. */
export type InvoiceStatus = "unpaid" | "partially_paid" | "paid" | "cancelled";

export interface InvoiceLine {
  itemId: string;
  /** Product name, e.g. "A4 Normal board". */
  title: string;
  /** Variant and options, e.g. "Extra ordinary finishing · 12 by 12". */
  detail: string | null;
  /** The product's catalog description, e.g. "We charge per sheet…". */
  description: string | null;
  qty: number;
  /** "Pc", "Sheet", "Service"… */
  unit: string | null;
  /** The agreed price per unit; null until priced ("To be confirmed" on a pro forma). */
  unitPrice: number | null;
  /** The catalog list price per unit, when the agreed price is below it (a discount); else null. */
  listUnitPrice: number | null;
  lineTotal: number | null;
  /** Where this item is, in the client's words ("Production", "Ready for delivery"…). */
  progress: string;
}

/** Who the invoice is from — the boss edits these (Payments → Invoices → Invoice settings). */
export interface InvoiceIssuer {
  companyName: string;
  address: string | null;
  phone: string | null;
  email: string | null;
  /** One term per entry, printed as bullets. */
  terms: string[];
  /** "For, <signatureCompany>" above the signature line. */
  signatureCompany: string | null;
  /** Top-left of every invoice; null = the app icon. */
  logoUrl: string | null;
  /** Above the signature line; null = left blank to sign by hand. */
  signatureUrl: string | null;
}

/** The settings form's fields (terms as one line per term). */
export interface InvoiceSettingsInput {
  companyName: string;
  address: string;
  phone: string;
  email: string;
  terms: string;
  signatureCompany: string;
  /** Set by uploading (startInvoiceImageUpload / confirmInvoiceImageUpload); null removes it. */
  logoUrl: string | null;
  signatureUrl: string | null;
}

export interface InvoiceView {
  /**
   * "invoice": the real invoice, generated by staff. "proforma": an estimate
   * shown before the order is confirmed / invoiced — catalog prices for
   * everything except photo books (priced after the client is called).
   */
  kind: "invoice" | "proforma";
  /** Pro forma only: false while some lines (photo books, unpriced items) still await a price. */
  complete: boolean;
  id: string;
  invoiceNo: string;
  issuedAt: string;
  dueDate: string | null;
  notes: string | null;
  status: InvoiceStatus;
  amount: number;
  /** Discount given on the lines: Σ (list − agreed price) × qty; 0 when none. amount is after it. */
  discount: number;
  paid: number;
  /** amount − paid, never below 0. */
  balance: number;
  order: {
    id: string;
    orderNo: string;
    placedAt: string;
    deliveryDate: string | null;
    cancelled: boolean;
    cancelReason: string | null;
  };
  client: { name: string; phone: string | null; email: string | null };
  issuer: InvoiceIssuer;
  lines: InvoiceLine[];
  /** Oldest first. */
  payments: OrderPaymentRecord[];
}

/** One line in the staff's price editor (generate / edit lines). */
export interface DraftLine {
  itemId: string;
  title: string;
  detail: string | null;
  qty: number;
  unit: string | null;
  /** The price already agreed for this line, else the catalog's, else null (staff must fill it in). */
  unitPrice: number | null;
  /** The catalog list price per unit, for showing a lower price as a discount; null when the line has none. */
  listUnitPrice: number | null;
  /** The discount agreed for this line before the order was confirmed (packages/lib/orders/pricing.ts). */
  agreedDiscount: LineDiscount | null;
}

/** The staff version adds the share link and the client's wallet balance. */
export interface StaffInvoiceView extends InvoiceView {
  shareUrl: string;
  /** The lines as the price editor needs them. */
  draftLines: DraftLine[];
  /** False when an item was added or re-quantified after invoicing: the lines no longer sum to the total. */
  linesMatchTotal: boolean;
  /** Null when the order has no client account. */
  walletBalance: number | null;
  createdByName: string;
}

export interface InvoiceListRow {
  id: string;
  invoiceNo: string;
  orderId: string;
  orderNo: string;
  clientName: string;
  issuedAt: string;
  dueDate: string | null;
  status: InvoiceStatus;
  amount: number;
  paid: number;
  balance: number;
}

/** What a client can open for their order: the invoice, or before that the pro forma (estimate). */
export interface ClientOrderDocument {
  kind: "invoice" | "proforma";
  href: string;
  /** The (estimated) total; for an incomplete pro forma, the priced lines only. */
  amount: number | null;
  /** Pro forma: false while photo books / unpriced items still await a price. */
  complete: boolean;
}

/** One change to an order's line discounts, for the staff discount history. Oldest first. */
export interface DiscountHistoryEntry extends LineDiscountChange {
  at: string;
  actorName: string;
}

/** What every invoice server action returns. `error` is always safe to show. */
export type InvoiceResult<T = undefined> = T extends undefined
  ? { ok: true } | { ok: false; error: string }
  : { ok: true; data: T } | { ok: false; error: string };
