-- Factory Order Tracker — invoices
--
-- One invoice per order, generated by staff from the order. Design notes:
-- lib/invoices/README.md. In short:
--
--   * An invoice doesn't hold money. What's been paid comes from the wallet
--     ledger (wallet_transactions rows with this order_id), and the total is
--     the order's own price (orders.quoted_price, fixed when the invoice is
--     generated). Status — Unpaid / Partially paid / Paid / Cancelled — is
--     worked out from those every time it's shown, so it can't drift.
--   * Installments are `payments` rows with order_id set, settled through
--     wallet_settle_payment: credited to the client's wallet and applied to
--     the order in one transaction. Overpaying leaves the rest as wallet
--     credit. A payment provider later settles the same way.
--   * share_token is the secret in the client's link (/invoice/<token>).
--     Anyone holding it can view that one invoice, nothing else; staff can
--     replace it to revoke a link that went to the wrong person.
--
-- Service-role only (RLS on, no policies), like the wallet tables: the public
-- invoice page reads through server code that looks the token up.

create table invoices (
  id              uuid primary key default gen_random_uuid(),
  order_id        uuid not null unique references orders(id) on delete restrict,
  -- 'INV-' + the order number, so staff and clients can match them at a glance.
  invoice_no      text not null unique,
  share_token     text not null unique,
  issued_at       timestamptz not null default now(),
  due_date        date,
  -- Printed on the invoice (payment terms, a thank-you…).
  notes           text,
  created_by_id   text,
  created_by_name text not null,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now(),
  constraint invoices_token_length check (length(share_token) >= 32)
);

create index invoices_issued_idx on invoices (issued_at desc);

alter table invoices enable row level security;
